---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install tools
    community.general.pipx:
      name: "{{ item }} "
      state: install
      executable: pipx
    with_items:
      - ansible
      - asciinema
      - aws-shell
      - black
      - chardet
      - cookiecutter
      - docker-compose
      # - gitsome
      - glances
      - glom
      - gpustat
      - howdoi
      - http-prompt
      - httpie
      - httpstat
      - invoke
      - ipython
      - iredis
      - isort
      - jc
      - jello
      - jupyterlab
      - kaggle
      - kube-shell
      - litecli
      - mlflow
      - mycli
      - mypy
      - percol
      - pgcli
      - pipx
      - poetry
      - pyinstaller
      - pylint
      - pytest
      - ranger-fm
      - rich-cli
      - saws
      - scapy
      - scrapy
      - shell-functools
      - supervisor
      - termtosvg
      - thefuck
      - tqdm
      - visidata
      - watchdog
      - wharfee
      - xonsh[full]
      - you-get
  - name: Configure aliases
    file:
      src: "{{ playbook_dir }}/configs/aliases"
      dest: ~/.aliases
      state: link
      force: no
  - name: Configure ipython
    git:
      repo: https://github.com/fmind/ipython.d
      dest: ~/.ipython
      depth: 1
  - name: Configure jupyter
    git:
      repo: https://github.com/fmind/jupyter.d
      dest: ~/.jupyter
      depth: 1
  - name: Configure xonsh
    file:
      src: "{{ playbook_dir }}/configs/xonshrc"
      dest: ~/.xonshrc
      state: link
      force: no
